default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: bootstrap3_development

test:
  <<: *default
  database: bootstrap3_test

production:
  <<: *default
  database: bootstrap3_production
  username: bootstrap3
  password: <%= ENV['BOOTSTRAP3_DATABASE_PASSWORD'] %>
